{% set data = load_setup_py_data() %}

package:
  name: python_example
  version: 0.0.1

# package:
#   name: {{ data.get('name') | lower }}
#   version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vvv .
  # script: python -m pip install --no-deps --ignore-installed .
  # script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('cxx') }}
    - pybind11>=2.10.0

  host:
    - python
    - pip
    - pybind11>=2.10.0

  run:
    - python
    # - numpy>=1.19
    # - scipy>=1.9
    # - matplotlib>=3.3
    # - graphviz>=0.16
    # - progressbar2>=4.0

about:
  summary: An example project built with pybind11.
  license_file: LICENSE

# about:
#   home: {{ data.get('url') }}
#   license: {{ data.get('license') }}
#   license_file: LICENSE
#   summary: {{ data.get('description') }}
